name: Publish npm package & GitHub Release

on:
  push:
    tags:
      - "*"

jobs:
  github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: yarn install --immutable

      - uses: ncipollo/release-action@v1
        with:
          artifacts: directusToData.js

  npm-publish:
    runs-on: ubuntu-latest
     # See https://docs.npmjs.com/trusted-publishers#github-actions-configuration
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - run: yarn install --immutable
      - run: npm publish
  